/**
 * sync-shared — regenerates every derived copy of the shared service modules.
 *
 * CANONICAL SOURCE:   js/services/<name>.js   (browser ES modules, no build step)
 * DERIVED COPIES:
 *   functions/shared/<name>.cjs               (CommonJS — Cloud Functions deploy
 *                                              only the functions/ dir)
 *   ../PennyHelm-Mobile/src/shared/<name>.js  (verbatim ESM — Metro bundles it;
 *                                              EAS builds from the mobile repo,
 *                                              so the copy must be committed there)
 *
 * Edit ONLY the canonical source, then run:  npm run sync:shared
 * Drift guards: tests/shared-access.test.js (functions copies, behavioral)
 * and tests/shared-sync.test.js (mobile copies, byte-exact).
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MOBILE_SHARED_DIR = path.join(root, '..', 'PennyHelm-Mobile', 'src', 'shared');

const SERVICES = ['financial-service', 'budget-service', 'category-service'];

const cjsHeader = (name) => `/**
 * CJS COPY of js/services/${name}.js for Cloud Functions.
 * Functions deploy only the functions/ dir, so the app ESM module is
 * unreachable here. GENERATED by scripts/sync-shared.mjs — DO NOT EDIT;
 * edit js/services/${name}.js and run \`npm run sync:shared\`.
 * Drift guard: tests/shared-access.test.js fails if this copy diverges.
 */
`;

const mobileHeader = (name) => `/**
 * GENERATED COPY of PennyHelm/js/services/${name}.js for the mobile app.
 * EAS builds from this repo, so the shared module must be committed here.
 * DO NOT EDIT — edit the canonical file in the web repo and run
 * \`npm run sync:shared\` there. Drift guard: PennyHelm/tests/shared-sync.test.js.
 */
`;

function toCjs(src, name) {
    const names = { fns: [], consts: [] };
    const body = src.split('\n').map((line) => {
        let m = line.match(/^export function (\w+)/);
        if (m) { names.fns.push(m[1]); return line.replace(/^export /, ''); }
        m = line.match(/^export const (\w+)/);
        if (m) { names.consts.push(m[1]); return line.replace(/^export /, ''); }
        if (/^export\b/.test(line)) {
            throw new Error(`${name}: unsupported export form: ${line}`);
        }
        return line;
    }).join('\n');
    const all = [...names.fns, ...names.consts];
    if (all.length === 0) throw new Error(`${name}: no exports found`);
    return `${cjsHeader(name)}${body.replace(/\s*$/, '\n')}\nmodule.exports = { ${all.join(', ')} };\n`;
}

let mobileSynced = true;
for (const name of SERVICES) {
    const src = fs.readFileSync(path.join(root, 'js', 'services', `${name}.js`), 'utf8');

    // Cloud Functions copy
    const cjsPath = path.join(root, 'functions', 'shared', `${name}.cjs`);
    fs.writeFileSync(cjsPath, toCjs(src, name));
    console.log(`synced ${path.relative(root, cjsPath)}`);

    // Mobile copy (verbatim source after the generated header)
    if (fs.existsSync(path.dirname(MOBILE_SHARED_DIR))) {
        fs.mkdirSync(MOBILE_SHARED_DIR, { recursive: true });
        const mobilePath = path.join(MOBILE_SHARED_DIR, `${name}.js`);
        fs.writeFileSync(mobilePath, mobileHeader(name) + src);
        console.log(`synced ${mobilePath}`);
    } else {
        mobileSynced = false;
    }
}
if (!mobileSynced) {
    console.log('note: ../PennyHelm-Mobile not found — mobile copies skipped');
}
console.log('done. Run `npm test` to confirm the drift guards pass.');
